
import Others.changes;
import Others.retrive;
import com.sun.org.apache.bcel.internal.generic.Select;
import hotel.managment.system.Facade;
import hotel.managment.system.Resident;
import hotel.managment.system.balance;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zead Fekry
 */
public class CheckIn extends javax.swing.JFrame {

    /**
     * Creates new form CheckIn
     */
    public CheckIn() {
        initComponents();
         ResultSet rs = retrive.retrivedata("select *from resident");
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        model.setRowCount(0);
        try
        {
            while (rs.next()) {
               model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)});
                
            }
            rs.close();
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, e);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        type_of_stay_combo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        type_of_room_combo = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<String>();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/all pages background.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 351, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nationallity ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 206, -1, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 236, 351, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Type Of Stay: ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 286, -1, -1));

        type_of_stay_combo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        type_of_stay_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Halfboard", "Fullboard", "Bed and Breakfast" }));
        type_of_stay_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_of_stay_comboActionPerformed(evt);
            }
        });
        getContentPane().add(type_of_stay_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 286, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Check In Date (Today)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 256, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ID Proof");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 130, -1, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 160, 349, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Duration");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 196, -1, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 215, 349, -1));

        type_of_room_combo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        type_of_room_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double", "Triple" }));
        type_of_room_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                type_of_room_comboItemStateChanged(evt);
            }
        });
        type_of_room_combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                type_of_room_comboMouseClicked(evt);
            }
        });
        type_of_room_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_of_room_comboActionPerformed(evt);
            }
        });
        getContentPane().add(type_of_room_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1081, 151, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Bed");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1007, 154, 43, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Room Number");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1007, 206, -1, -1));

        jComboBox4.setEditable(true);
        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1007, 229, 240, -1));

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Allocate Room");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1007, 282, -1, -1));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Customer Check In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 11, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "cust_name", "nationalid", "roomid", "duration", "boarding", "Room_type", "Check_Cost"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 620, 180));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, 25, 25));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 90, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 90, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 110, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -50, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 0, 0));
        jButton3.setText("Edit selected resident");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 0, 0));
        jButton4.setText("Delete selected resident");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void type_of_stay_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_of_stay_comboActionPerformed
        // TODO add your handling code here:
        String selected_text =type_of_stay_combo.getSelectedItem().toString();
        System.out.println(selected_text);
    }//GEN-LAST:event_type_of_stay_comboActionPerformed

    private void type_of_room_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_of_room_comboActionPerformed
  
    }//GEN-LAST:event_type_of_room_comboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
  
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void type_of_room_comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_type_of_room_comboMouseClicked
           
    }//GEN-LAST:event_type_of_room_comboMouseClicked

    private void type_of_room_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_type_of_room_comboItemStateChanged
         jComboBox4.removeAllItems();
        String roomtype=(String)type_of_room_combo.getSelectedItem();
   
   try
   {
     
       ResultSet rs =retrive.retrivedata("select *from rooms where roomtype='"+roomtype+"' and status='Not BOOKED'");
       while (rs.next()) {
          jComboBox4.addItem(rs.getString(1));   
       }
   }
   catch(Exception e)
   {
       JOptionPane.showMessageDialog(null, e);
   }
    }//GEN-LAST:event_type_of_room_comboItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
        System.out.println("yabo se7a"+Integer.parseInt(jTextField2.getText().toString()));
        
        Facade reserv = new Facade(Integer.parseInt(jTextField5.getText()), jTextField1.getText(), Integer.parseInt(jTextField3.getText()),
                Integer.parseInt((String)jComboBox4.getSelectedItem()),Integer.parseInt(jTextField8.getText()), 
                (String)type_of_stay_combo.getSelectedItem(),(String) type_of_room_combo.getSelectedItem(),Integer.parseInt(jTextField2.getText().toString())
        ,Integer.parseInt(jTextField4.getText().toString()),Integer.parseInt(jTextField6.getText().toString()));
         
        reserv.ConfirmResirvation();
          
          
      
      

           ResultSet rs = retrive.retrivedata("select *from resident");
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        model.setRowCount(0);
        try
        {
            while (rs.next()) {
               model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)});
                
            }
            rs.close();
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, e);
        }  
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
      DefaultTableModel tblmodel=(DefaultTableModel)jTable2.getModel();
       int id=Integer.parseInt((tblmodel.getValueAt(jTable2.getSelectedRow(),0).toString()));
       String name=tblmodel.getValueAt(jTable2.getSelectedRow(),1).toString();
       int nationalid=Integer.parseInt((tblmodel.getValueAt(jTable2.getSelectedRow(),2).toString()));
       int roomid=Integer.parseInt((tblmodel.getValueAt(jTable2.getSelectedRow(),3).toString()));
       int duration=Integer.parseInt((tblmodel.getValueAt(jTable2.getSelectedRow(),4).toString()));
       String boardingtype=tblmodel.getValueAt(jTable2.getSelectedRow(),5).toString();
       String room_type=tblmodel.getValueAt(jTable2.getSelectedRow(),6).toString();
       int checkcost=Integer.parseInt((tblmodel.getValueAt(jTable2.getSelectedRow(),7).toString()));
               // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      DefaultTableModel tblmodel=(DefaultTableModel)jTable2.getModel();
       String id=((tblmodel.getValueAt(jTable2.getSelectedRow(),0).toString()));
       String name=tblmodel.getValueAt(jTable2.getSelectedRow(),1).toString();
       String nationalid=((tblmodel.getValueAt(jTable2.getSelectedRow(),2).toString()));
       String roomid=((tblmodel.getValueAt(jTable2.getSelectedRow(),3).toString()));
       String duration=((tblmodel.getValueAt(jTable2.getSelectedRow(),4).toString()));
       String boardingtype=tblmodel.getValueAt(jTable2.getSelectedRow(),5).toString();
       String room_type=tblmodel.getValueAt(jTable2.getSelectedRow(),6).toString();
       String checkcost=((tblmodel.getValueAt(jTable2.getSelectedRow(),7).toString()));


      Edit_resident edt=new Edit_resident();
         edt.namez.setText(name);
         edt.nationalid.setText(nationalid);
         edt.id.setText(id);
         edt.roomid.setText(roomid);
         edt.duration.setText(duration);
         edt.boarding.setText(boardingtype);
         edt.roomtype.setText(room_type);
         edt.cost.setText(checkcost);

         edt.setVisible(true);
       int index=jTable2.getSelectedRow();
        DefaultTableModel tbleModel=(DefaultTableModel) jTable2.getModel();

        if(jTable2.getSelectedRowCount()==1)
        {

        }
        else if(jTable2.getSelectedRowCount()==0)
                {
                    JOptionPane.showMessageDialog(this, "Table is empty");
                }
         ResultSet rs = retrive.retrivedata("select *from resident");
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        model.setRowCount(0);
        try
        {
            while (rs.next()) {
               model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)});

            }
            rs.close();
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, e);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       int index=jTable2.getSelectedRow();
        DefaultTableModel tbleModel=(DefaultTableModel) jTable2.getModel();
        int id = Integer.parseInt(tbleModel.getValueAt(index, 0).toString());
        int roomid = Integer.parseInt(tbleModel.getValueAt(index, 3).toString());
        if(jTable2.getSelectedRowCount()==1)
        {
           try{
               int a =JOptionPane.showConfirmDialog(null, "Do you want really to delete this worker","select",JOptionPane.YES_NO_OPTION);
           if(a==0){
               changes.setData("UPDATE rooms SET status='Not BOOKED' WHERE idrooms='"+roomid+"'","deleting in progress");
               changes.setData("DELETE FROM resident WHERE ID='"+id+"'", "deleted successfully");
               tbleModel.removeRow(jTable2.getSelectedRow());
           }}
           catch(Exception e)
           {
               JOptionPane.showMessageDialog(null, e);
           }
        }
        else if(jTable2.getSelectedRowCount()==0)
                {
                    JOptionPane.showMessageDialog(this, "Table is empty");
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JComboBox type_of_room_combo;
    private javax.swing.JComboBox type_of_stay_combo;
    // End of variables declaration//GEN-END:variables
}
